<a href="https://colab.research.google.com/github/vardaprajapati/Books-Python/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#NUMPY: PACKAGE FOR MULTIDIMENSIONAL ARRAY
import numpy as np
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [ ]:
list_of_lists=[[1,2],[2,3],[7,8]]
sample_matrix=np.array(list_of_lists)

In [ ]:
sample_matrix

array([[1, 2],
       [2, 3],
       [7, 8]])

In [ ]:
np.arange(1,7)

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
np.arange(1,50,6)

array([ 1,  7, 13, 19, 25, 31, 37, 43, 49])

In [ ]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros(4,int) #OR (4,dtype=int)

array([0, 0, 0, 0])

In [ ]:
np.ones(40)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones(20,str)

array(['1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1',
       '1', '1', '1', '1', '1', '1', '1'], dtype='<U1')

In [ ]:
np.ones(40,dtype=str)

array(['1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1',
       '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1',
       '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1',
       '1'], dtype='<U1')

In [ ]:
np.zeros((2,5),int) # 2 rows and 5 coluMNS

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
###CREATE AN ARRAY OF ZEROS WITH 2 ROWS AND 10 COLUMNS


In [ ]:
#np.linspace()
#np.eye()  identity matrix
#np.random.rand()
#np.random.randn() negative numbers btw them too
#np.random.randint(0,100,20)  , 20 values will come
#sample_array.reshape()

In [ ]:
np.linspace(6,70,6)

array([ 6. , 18.8, 31.6, 44.4, 57.2, 70. ])

In [ ]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
np.eye(4,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.]])

In [ ]:
np.random.randint(1,8.9)

4

In [ ]:
sample_arr=np.arange(20)
sample_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
rand_arr=np.random.randint(0,90,15)
rand_arr

array([59, 56, 36, 26, 43,  8, 75, 12, 68, 39, 58,  1, 36, 67, 22])

In [ ]:
sample_arr.reshape(2)

ValueError: ignored

In [ ]:
rand_arr.min()

1

In [ ]:
rand_arr.argmax()

6

In [ ]:
a=np.eye(6)
a

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
np.random.rand(2,3)

array([[0.83759606, 0.03053418, 0.61620209],
       [0.55185337, 0.88022825, 0.57126829]])

In [ ]:
a.T

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
###SLICING###

In [ ]:
samp_arr=np.arange(4,7)
samp_arr

array([4, 5, 6])

In [ ]:
samp_arr[2]

6

In [ ]:
samp_arr[1:3]

array([5, 6])

In [ ]:
samp_arr[:]=100

In [ ]:
samp_arr

array([100, 100, 100])

In [ ]:
samp_arr=np.arange(1,17)
samp_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [ ]:
samp_arr[3:7]=89

In [ ]:
samp_arr

array([ 1,  2,  3, 89, 89, 89, 89,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [ ]:
#### 2D ARRAYS ###

In [ ]:
import numpy as np

In [ ]:
samp_matrix=np.array([[30,40,23],[12,34,17],[78,98,20]])
samp_matrix

array([[30, 40, 23],
       [12, 34, 17],
       [78, 98, 20]])

In [ ]:
samp_matrix[0:2,2]    # 0:2 - 0,1 rows 
                      # 2   - col

array([23, 17])

In [ ]:
samp_matrix[0:3,2]

array([23, 17, 20])

In [ ]:
samp_matrix[2,:]       # 2nd row and whole col

array([78, 98, 20])

In [ ]:
samp_matrix[:,(2,1)]   #all rows and 2 & 1 col

array([[23, 40],
       [17, 34],
       [20, 98]])

In [ ]:
a=samp_arr=np.arange(1,30)

In [ ]:
samp_arr+samp_arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58])

In [ ]:
np.exp(samp_arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08,
       1.31881573e+09, 3.58491285e+09, 9.74480345e+09, 2.64891221e+10,
       7.20048993e+10, 1.95729609e+11, 5.32048241e+11, 1.44625706e+12,
       3.93133430e+12])

In [ ]:
np.sqrt(a)  # sq root 

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
       4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
       5.09901951, 5.19615242, 5.29150262, 5.38516481])

In [ ]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227,
       3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582,
       3.25809654, 3.29583687, 3.33220451, 3.36729583])

In [ ]:
np.max(a) #np.min()

29

In [ ]:
np.argmin(a) #np.armax()

0

In [ ]:
np.std(a)  # standard deviation

8.366600265340756

In [ ]:
np.var(a) #variant

70.0

In [ ]:
np.mean(a)

15.0

In [ ]:
array=np.random.randn(3,6)
array

array([[-1.05546059, -1.68154077,  0.38860621,  1.76217584, -0.06421689,
         0.94831414],
       [ 1.21337965,  0.06851834, -0.32374187,  0.80303648,  0.28227978,
        -0.84349614],
       [-0.15830918, -1.07901803,  0.63011018,  0.72578731, -1.07124521,
         0.69781253]])

In [ ]:
#np.unique(parameter)

In [ ]:
np.round(array,decimals=2)

array([[-1.06, -1.68,  0.39,  1.76, -0.06,  0.95],
       [ 1.21,  0.07, -0.32,  0.8 ,  0.28, -0.84],
       [-0.16, -1.08,  0.63,  0.73, -1.07,  0.7 ]])